-- =====================================================
-- Add design_submitted_date to deal_stages + rebuild deals_view
-- =====================================================

-- 1. Add column
ALTER TABLE deal_stages ADD COLUMN IF NOT EXISTS design_submitted_date date;

-- 2. Rebuild deals_view with design_submitted_date included
DROP VIEW IF EXISTS deals_view;
CREATE VIEW deals_view AS
SELECT
  d.id,
  d.created_at,
  d.sales_rep,
  d.company,
  d.customer_name,
  d.appointment_setter,
  d.call_center_appointment_setter,
  d.company_barayev_input,
  d.kw_system,
  d.agent_cost_basis,
  d.agent_cost_basis_sold_at,
  d.net_price_per_watt,
  d.date_closed,
  d.contract_value,
  d.total_adders,
  d.contract_net_price,
  d.rev,
  d.gross_profit,
  d.visionary_paid_out_commission,
  d.nova_nrg_customer_adders,
  d.agent_payout,
  d.manager,
  d.manager_amount,
  d.status,
  d.p1_nova_nrg_paid,
  d.site_survey_date_completed,
  d.site_survey_status,
  d.owed_money,
  d.paid_bonus,
  d.fee_charges,
  d.notes,
  d.paid_nova_nrg_rev_date,
  d.paid_nova_nrg_rev,
  d.sales_partner_redline,
  d.sales_redline_contract,
  d.install_partner,
  d.state,
  d.teams,
  d.activated,
  d.online_deal,
  d.call_center_lead,
  d.month_year,
  d.commission_structure,
  d.paid_nova_nrg_p1_date,
  d.paid_nova_nrg_p1_amount,
  d.revenue,
  d.paid_nova_nrg_p2_rev_date,
  d.paid_nova_nrg_p1_p2_rev_amount,
  d.paid_nova_nrg_post_p2_date,
  d.paid_nova_nrg_post_p2_rev_amount,
  d.nova_nrg_reversal_date,
  d.nova_nrg_reversal_amount,
  d.nova_nrg_fee_amount,
  d.paid_visionary_p1_date,
  d.paid_visionary_p1_amount,
  d.visionary_revenue,
  d.paid_visionary_p2_date,
  d.paid_visionary_p1_p2_amount,
  d.paid_visionary_post_p2_date,
  d.paid_visionary_post_p2_amount,
  d.p1_visionary_reversal_date,
  d.p1_visionary_reversal_amount,
  d.visionary_fee_amount,
  d.paid_agent_p1_date,
  d.paid_agent_p1_amount,
  d.agent_pay,
  d.paid_agent_p2_date,
  d.paid_agent_p1_p2_amount,
  d.paid_agent_post_p2_date,
  d.paid_agent_post_p2_amount,
  d.p1_agent_reversal_date,
  d.p1_agent_reversal_amount,
  d.agent_fee_amount,
  d.agent_net_price,
  d.only_agent_net_price_accounts,
  d.agent_payout_tableau,
  d.setter,
  d.opportunity,
  d.setter_paid_date,
  d.manager_paid_date,
  d.nova_nrg_rev_after_fee_override,
  d.visionary_rev_after_fee_override,
  d.agent_rev_after_fee_override,
  d.only_agent_net_price_accounts_override,
  d.agent_payout_tableau_override,
  d.gp_percent_override,
  d.nova_nrg_rev_after_fee_amount,
  d.visionary_rev_after_fee_amount,
  d.agent_rev_after_fee_amount,
  d.gp_percent,
  d.first_name,
  d.last_name,
  d.phone_number,
  d.email_address,
  d.street_address,
  d.city,
  d.postal_code,
  d.country,
  d.sale_type,
  d.battery_job,
  d.type_of_roof,
  d.panel_type,
  d.panel_amount,
  d.roof_work_needed,
  d.roof_work_progress,
  d.permit_ahj_info,
  d.permit_fees,
  d.permit_number,
  d.permit_status,
  d.permit_fees_paid,
  d.hoa,
  d.hoa_name,
  d.hoa_forms_completed,
  d.pricing_locked,
  d.pricing_locked_at,
  -- deal_source
  d.deal_source,
  -- From deal_stages join
  s.design_ready_date,
  s.design_submitted_date,
  s.permit_submitted_date,
  s.permit_approved_date,
  s.install_1_racks_date,
  s.install_2_panel_landed_date,
  s.paid_date,
  s.pto_date,
  -- From deal_utility join
  u.utility_company,
  u.ntp_status,
  u.ic_status,
  u.meter_status
FROM deals d
LEFT JOIN deal_stages s ON d.id = s.deal_id
LEFT JOIN deal_utility u ON d.id = u.deal_id;
